### ISSUE TITLE
updating figures

### ISSUE THREAD

**Issue by katherinekeller** [katherinekeller/cascadia-margin-lipids#14]
1) put all data into 1 ternary diagram, add tick marks and values from 0 - 1
2) update labels: planktonic/autotrophic, benthic/methane-cycling, benthic/non-methane cycling
3) change cren regio label to G5
4) change colors for locations: Astoria: 'darkteal', HR: 'orangered', MC: 'olive'

**Comment by markmbaum** [comment]
I did numbers 1 and 2 above, for example:

![image](https://github.com/katherinekeller/cascadia-margin-lipids/assets/18745581/04adc227-51cd-4500-8f60-2050cde98bb1)
