### ISSUE TITLE
add tex86 to model

### ISSUE THREAD

**Issue by katherinekeller** [katherinekeller/cascadia-margin-lipids#27]
<img width="506" alt="Screenshot 2024-03-19 at 10 35 50 AM" src="https://github.com/katherinekeller/cascadia-margin-lipids/assets/101064911/2e6e2339-1c09-4b41-893a-475959a115e4">

should be based on matrix M.

**Comment by markmbaum** [comment]
I added TEX86 nodes for both the `X` and `M` matrices, called `Community TEX86` and `Location TEX86`.

The updated model results are [here](https://drive.google.com/file/d/1xy6O7mIDUanRZhkagx910IEf1IS0Z_lN/view?usp=sharing).

Here is the updated model readout:

<img width="704" alt="Screenshot 2024-03-19 at 3 51 01 PM" src="https://github.com/katherinekeller/cascadia-margin-lipids/assets/18745581/d7b79dfb-e892-442b-b785-53b8e665f581">

Feel free to merge #28 if this is all ok, and delete the branch.
